### ISSUE TITLE
How do the moon phases work exactly?

### ISSUE THREAD

**Issue by trosel** [Sudrien/WatchyOrbital#3]
I see the drawMoon method, but I think all of the magic happens in the "sun" object (`sun.moonPhase(unix_time)`) which seems to come from `sunset.h`. 

I can't find where the SunSet library is. Is the moon phase data hard coded into that? I'm wondering if it's calculating the phase based on an algorithm or if it's based on an API and requires internet access every so often?

**Comment by Sudrien** [comment]
In the readme, you will note the dependacy on the Sunset library - currently 1.1.7. Specificly, https://github.com/buelowp/sunset

It is algorithm based. Also, available in the arduino library listing.
